name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
        with:
          save_cache: 'true'

      - parallel:
          - name: Lint
            run: bun run lint
          - name: Lint styles
            run: bun run stylelint
          - name: Typecheck
            run: bun run typecheck

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Java
        id: java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
        background: true
      - uses: ./.github/actions/setup
      - wait: java
      - run: bun test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
      - run: |
          NODE_ENV=production \
          NEXT_PUBLIC_FIREBASE_API_KEY=dummy \
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=dummy \
          NEXT_PUBLIC_FIREBASE_PROJECT_ID=dummy \
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=dummy \
          NEXT_PUBLIC_FIREBASE_APP_ID=dummy \
          NEXT_PUBLIC_FIREBASE_FIRESTORE_DATABASE_ID=dummy \
          NEXT_PUBLIC_DISCORD_WEBHOOK_URL=dummy \
          bun run build
